FROM golang:1.24.4-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN apk add --no-cache build-base sqlite-dev
RUN go build -o main .

FROM alpine:latest

RUN apk add --no-cache sqlite-libs

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 3000

CMD ["./main"]
