name: Build and Deploy Backend Docker Image

on:
    workflow_dispatch:
        inputs:
            tags:
                description: 'Tag (e.g. v1.0.0)'
                required: true
                type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Validate tag format
        run: |
          echo "Validating tag: ${{ github.event.inputs.tags }}"

          if ! [[ "${{ github.event.inputs.tags }}" =~ ^v[0-9]+(\.[0-9]+)*$ ]]; then
            echo "❌ Invalid tag format. Expected format: v<major>.<minor>[.<patch>], e.g. v1.0 or v1.2.3"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: build backend docker image
        run: |
          cd backend
          docker build --platform=linux/amd64 -t oyetanu/nodus-backend:${{ github.event.inputs.tags }} .

      - name: Image build size
        run: |
          docker image inspect oyetanu/nodus-backend:${{ github.event.inputs.tags }} \
          | jq '.[].Size / 1024 / 1024 | round' \
          | awk '{print $1 " MB"}'